### ISSUE TITLE
bug for “position”: 不是“QMouseEvent”的成员。

### ISSUE THREAD

**Issue by molyswu** [WangHongshuo/TFT-LCD_defects_detecter-Qt-opencv#2]
Hi

1.TFT-LCD_defects_detecter-Qt-opencv\ImageWidget-Qt\ImageWidget.cpp:823: error: C2039: “position”: 不是“QMouseEvent”的成员。
2.TFT-LCD_defects_detecter-Qt-opencv\ImageWidget-Qt\ImageWidget.cpp:823: error: C2660: “ImageWidget::sendLeftClickedPosInWidgetSignal”: 函数不接受 1 个参数。

molys

**Comment by WangHongshuo** [comment]
*\mingw_64\include\QtGui\qevent.h:261
```
QT_DEPRECATED_VERSION_X_6_0("Use position()")
inline int x() const { return qRound(position().x()); }
```
Qt 6.0以上高版本推荐使用`position().x()`，低版本可继续使用`x()`
